name: kterm
description: kterm is a fast and fully-featured terminal emulator for Flutter applications, with support for mobile and desktop platforms.
version: 1.4.0
homepage: https://github.com/lbp0200/kterm.dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  meta: ^1.3.0
  flutter:
    sdk: flutter
  zmodem_lbp: ^0.0.10
  kitty_protocol: ^1.3.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^5.0.0
  mockito: ^5.3.1
  build_runner: ^2.1.1

flutter:
